name: ci

on:
  push:
    branches:
      - 'handbrake-cli-x86-64'

#on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu20.04 (x86-64)
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          #arch: aarch64
          #distro: ubuntu20.04
          arch: none
          distro: none
          base_image: ubuntu:20.04

          # Not required, but speeds up builds
          #githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
            mkdir -p "/tmp/build"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            --volume "/tmp/build:/build"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: handbrake-cli-x86-64

          # The shell to run commands with in the container
          shell: /bin/sh

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            apt-get update -qq -y
            apt-get install -qq -y autoconf automake autopoint appstream build-essential cmake git libass-dev libbz2-dev libfdk-aac-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libgraphite2-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libnuma-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libturbojpeg0-dev libvorbis-dev libx264-dev libxml2-dev libvpx-dev m4 make meson nasm ninja-build patch pkg-config tar zlib1g-dev 
          # Produce a binary artifact and place it in the mounted volume
          run: |
            cd /build
            git clone https://github.com/HandBrake/HandBrake.git
            cd HandBrake
            apt autoremove -y
            #git tag --list | grep ^1\.6\.
            #git checkout refs/tags/$(git tag -l | grep -E '^1\.6\.[0-9]+$' | tail -n 1)

            ./configure --launch-jobs=$(nproc) --launch --disable-gtk --enable-fdk --enable-x265 LDFLAGS="-static -static-libgcc -static-libstdc++" >> /artifacts/logs.txt 2>&1
            ./configure --launch-jobs=$(nproc) --launch  --enable-fdk --enable-x265 LDFLAGS="-static-libass" >> /artifacts/logs.txt 2>&1
            cd build
            cp HandBrakeCLI handbrake-cli
            #apt install binutils patchelf python3-pip -y
            #pip3 install staticx
            #staticx HandBrakeCLI handbrake-cli
            chmod +x handbrake-cli
            ./handbrake-cli --version
            chmod 777 handbrake-cli
            cp handbrake-cli /artifacts/HandBrakeCLI
            sha256sum ./handbrake-cli > /artifacts/HandBrakeCLI.sha256sum
            md5sum ./handbrake-cli > /artifacts/HandBrakeCLI.md5sum
            echo "Copied to /artifacts"

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"

      - name: move logs
        if: always()
        run: |
          cp "${PWD}/artifacts/logs.txt" "${PWD}/"

      - uses: actions/upload-artifact@v3
        with:
          name: HandBrakeCLI_x86-64
          path: artifacts

      - name: cleanup
        if: always()
        run: |
          rm -rf "${PWD}/artifacts/" "${PWD}/HandBrake/"

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: commit logs
        if: always()
        with:
          commit_message: 'logging...'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Nubuki-all
          commit_user_email: 121189493+Nubuki-all@users.noreply.github.com
          commit_author: Nubuki-all <121189493+Nubuki-all@users.noreply.github.com>
